name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  root:
    runs-on: ubuntu-latest
    steps:
    - name: succeed
      run: 'true'

  stage-1-1:
    runs-on: ubuntu-latest
    needs: root
    steps:
    - name: succeed
      run: 'true'

  stage-1-2:
    runs-on: ubuntu-latest
    needs: root
    steps:
    - name: succeed
      run: 'true'

  stage-2-1:
    runs-on: ubuntu-latest
    needs: [stage-1-1, stage-1-2]
    steps:
    - name: succeed
      run: 'true'

  stage-2-2:
    runs-on: ubuntu-latest
    needs: [stage-1-1, stage-1-2]
    steps:
    - name: succeed
      run: 'true'

  fail:
    runs-on: ubuntu-latest
    needs: [stage-2-1, stage-2-2]
    steps:
    - name: fail
      run: 'false'

  dependent-on-fail:
    runs-on: ubuntu-latest
    needs: [fail]
    steps:
    - name: fail
      run: 'false'
